import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/forecast/daily">
            <p><a>Daily</a> Weather</p>
          </Link>
        </h1>
        <h1 className={styles.title}>
          <Link href="/forecast/fourday">
            <p><a>4-day</a> Weather</p>
          </Link>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://openweathermap.org/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/openweather.png" alt="Vercel Logo" width={84} height={38} />
          </span>
        </a>
      </footer>
    </div>
  )
}
